server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 512
  error:
    include-stacktrace: always
    include-exception: true
spring:
  main:
    allow-circular-references: true
  application:
    name: newlangs
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/数据库名称?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: 数据库名称
      password: 数据库密码
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
    token-name: accessToken
    timeout: -1
    active-timeout: -1
    is-concurrent: true
    is-share: false
    token-style: tik
    is-log: false